language: generic

env:
  - PPA=yes

install:
  - if [ x"$PPA" == "xyes" ] ; then sudo add-apt-repository ppa:pi-rho/dev -y; fi
  - sudo apt-get update -q
  - sudo apt-get install vim-nox
  - git clone https://github.com/thinca/vim-themis

before_script:
  - vim --version

script:
  - ./vim-themis/bin/themis
